# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aflami' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aflami
pod 'SwiftyJSON'
pod 'Moya'
pod 'RealmSwift'

pod 'SVProgressHUD'
pod 'ChameleonFramework'
pod 'SDWebImage'
pod 'Cosmos'

target 'AflamiTests' do
  inherit! :search_paths
end

end
